tubaNWeb/Controllers/PreviewAdminController.cs
using tubaNWeb.CommonClass;
using tubaNWeb.Models.Preview;
using Microsoft.AspNetCore.Mvc;
using MySql.Data.MySqlClient;
using System.Text;

namespace tubaNWeb.Controllers
{
	public class PreviewAdminController : Controller
    {        
    }
}

tubaNWeb/Controllers/PreviewAlbumController.cs
using tubaNWeb.CommonClass;
using tubaNWeb.Models.Preview;
using Microsoft.AspNetCore.Mvc;
using MySql.Data.MySqlClient;

namespace tubaNWeb.Controllers
{
	public class PreviewAlbumController : Controller
    {
		[HttpGet]
		public IActionResult Title(int sort)
        {
			HttpContext.Session.SetString("MainMenu", "Preview");

			if (HttpContext.Session.GetString("UserId") == null)
            {
                return RedirectToAction("Login", "Account");
            }

			if (sort <= 0)
			{
				return RedirectToAction("Login", "Account");
			}

			List<Video> titleList = new List<Video>();
            using (MySqlConnection conn = DBManager.Instance.PreviewConnection)
			{
				string query = string.Empty;

				switch (sort)
				{
					case 1:
						query = string.Format("SELECT uid, name, imagelink, modifydate, sortnumber FROM videomanager.title ORDER BY modifydate ASC");
						ViewData["SortName"] = "수정일 (오름차순)";
						break;
					case 2:
						query = string.Format("SELECT uid, name, imagelink, modifydate, sortnumber FROM videomanager.title ORDER BY modifydate DESC");
						ViewData["SortName"] = "수정일 (내림차순)";
						break;
					case 3:
						query = string.Format("SELECT uid, name, imagelink, modifydate, sortnumber FROM videomanager.title ORDER BY sortnumber ASC");
						ViewData["SortName"] = "번호 (오름차순)";
						break;
					case 4:
						query = string.Format("SELECT uid, name, imagelink, modifydate, sortnumber FROM videomanager.title ORDER BY sortnumber DESC");
						ViewData["SortName"] = "번호 (내림차순)";
						break;

					default:
						query = string.Format("SELECT uid, name, imagelink, modifydate, sortnumber FROM videomanager.title ORDER BY modifydate ASC");
						ViewData["SortName"] = "수정일 (오름차순)";
						break;
				}

				MySqlCommand cmd = new MySqlCommand(query, conn);
				try
				{
					using (MySqlDataReader reader = cmd.ExecuteReader())
					{
						while (reader.Read())
						{
							Video video= new Video();
                            video.UID = reader.GetUInt32("uid");
                            video.SortNumber = reader.GetUInt32("sortnumber");
                            video.Name = reader.GetString("name");
                            video.ImageLink = reader.GetString("imagelink");
							video.Date = reader.GetString("modifydate");
							titleList.Add(video);
                        }
					}
				}
				catch (MySqlException ex)
				{
					LogManager.Instance.Log(ex.ToString());
				}
			}

			ViewBag.TitleList = titleList;

            return View();
        }

		[HttpGet]
		public IActionResult Episode(uint uid, int sort)
		{
            if (HttpContext.Session.GetString("UserId") == null)
            {
                return RedirectToAction("Login", "Account");
            }

			if (uid <= 0 || sort <= 0)
			{
				return RedirectToAction("Login", "Account");
			}

			HttpContext.Session.SetInt32("CurTitle", (int)uid);			
			List<EpisodeData> episodeList = new List<EpisodeData>();
            using (MySqlConnection conn = DBManager.Instance.PreviewConnection)
            {
                string query = string.Empty;

				switch (sort)
                {
                    case 1:
						query = string.Format("SELECT * FROM videomanager.episode WHERE titleuid = {0} ORDER BY modifydate ASC", uid);
						ViewData["SortName"] = "수정일 (오름차순)";
						break;
					case 2:
						query = string.Format("SELECT * FROM videomanager.episode WHERE titleuid = {0} ORDER BY modifydate DESC", uid);
						ViewData["SortName"] = "수정일 (내림차순)";
						break;
					case 3:
						query = string.Format("SELECT * FROM videomanager.episode WHERE titleuid = {0} ORDER BY sortnumber ASC", uid);
						ViewData["SortName"] = "번호 (오름차순)";
						break;
					case 4:
						query = string.Format("SELECT * FROM videomanager.episode WHERE titleuid = {0} ORDER BY sortnumber DESC", uid);
						ViewData["SortName"] = "번호 (내림차순)";
						break;

					default:
						query = string.Format("SELECT * FROM videomanager.episode WHERE titleuid = {0} ORDER BY modifydate ASC", uid);
						ViewData["SortName"] = "수정일 (오름차순)";
						break;
                }

                MySqlCommand cmd = new MySqlCommand(query, conn);
                try
                {
                    List<uint> uidList = new List<uint>();
                    using (MySqlDataReader reader = cmd.ExecuteReader())
                    {                        
                        while (reader.Read())
                        {
                            EpisodeData episodeData = new EpisodeData();
							episodeData.EpisodeName = reader.GetString("name");
							episodeData.SortNumber = reader.GetUInt32("sortnumber");
							episodeData.Whatwork1 = reader.GetByte("whatwork1");
							episodeData.Whatwork2 = reader.GetByte("whatwork2");
							episodeData.Whatwork3 = reader.GetByte("whatwork3");

							episodeData.ImagePath = reader.GetString("imagelink");
							episodeData.AnimeticPath = reader.GetString("videolink1");
							episodeData.AnimationPath = reader.GetString("videolink2");
							episodeData.FinalPath = reader.GetString("videolink3");

							episodeData.Date = reader.GetString("modifydate");
							episodeData.Uid = reader.GetUInt32("uid");
							episodeList.Add(episodeData);
                            uidList.Add(episodeData.Uid);
                        }  
                    }

                    for (int i = 0; i < uidList.Count; i++)
                    {
                        query = string.Format("SELECT avg(star) FROM videomanager.comment WHERE episodeuid = {0}", uidList[i]);
                        cmd.CommandText = query;

                        object scalar = cmd.ExecuteScalar();
						if (scalar is DBNull)
						{
                            episodeList[i].Rating = 0f;
                            continue;
						}

                        float rating = (float)Convert.ToDouble(scalar);
                        float fixedRating = (float)Math.Round(rating * 2, MidpointRounding.ToPositiveInfinity) / 2; // MidpointRounding.AwayFromZero
						episodeList[i].Rating = fixedRating;
                    }
                }
                catch (MySqlException ex)
                {
                    LogManager.Instance.Log(ex.ToString());
					return View(ex.ToString());
				}
            }

            ViewBag.EpisodeList = episodeList;
			ViewBag.titleUID = uid;


			return View();
		}
	}
}

tubaNWeb/Controllers/PreviewReviewController.cs
using tubaNWeb.CommonClass;
using tubaNWeb.Models.Preview;
using Microsoft.AspNetCore.Mvc;
using MySql.Data.MySqlClient;
using System.Data;
using System.Text;

namespace tubaNWeb.Controllers
{
	public class PreviewReviewController : Controller
	{
	}
}

tubaNWeb/Views/PreviewAlbum/Episode.cshtml
@using tubaNWeb.Models.Preview

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
	Layout = "_LayoutPreview";
	ViewData["Title"] = "에피소드";

	int ratingI = 0;
	int ratingJ = 0;
	string str = string.Empty;

	string[,] starCheck = new string[ViewBag.EpisodeList.Count, 10];
	float starRating = 0.5f;
	for (int i = 0; i < starCheck.GetLength(0); i++)
	{
		for (int j = 0; j < starCheck.GetLength(1); j++)
		{
			if (ViewBag.EpisodeList[i].Rating == starRating)
			{
				starCheck[i, j] = "checked";
				break;
			}
			starRating += 0.5f;
		}
		starRating = 0.5f;
	}

	bool isAdmin = false;
	if (Context.Session.GetString("UserId") != null)
	{
		string userId = Context.Session.GetString("UserId");
		if (userId.ToLower().Equals("admin"))
		{
			isAdmin = true;
		}
	}
}



<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
<link rel="stylesheet" href="~/preview/css/starrating.css" type="text/css" />
<style>
	/*	.bd-placeholder-img {
			font-size: 1.125rem;
			text-anchor: middle;
			-webkit-user-select: none;
			-moz-user-select: none;
			user-select: none;
		}

		@@media (min-width: 768px) {
			.bd-placeholder-img-lg {
				font-size: 3.5rem;
			}
		}*/

	.container {
		padding-left: 0;
		width: 1400px !important;
		max-width: none !important;
		overflow: hidden; /*어긋난 정렬 수정*/
	}

	@@media (max-width: 300px) {
		.container {
			width: 300px !important;
		}
	}

	/*카드 이미지 크기조절*/
	.card-img-top {
		height: 15rem;
		/*object-fit: cover;*/
		background-size: cover;
	}

	/*카드 버튼 위로*/
	.card .btn {
		z-index: 2;
		position: relative;
	}

/*	.dropdown :not(.header) {
		margin-top: 50px;
	}*/

	/*별 크기조절*/
	.rating > label:before {
		margin: 5px;
		font-size: 1.25em;
		font-family: FontAwesome;
		display: inline-block;
		content: "\f005";
	}

		.space {
		width: 5px;
		height: auto;
		display: inline-block;
	}
</style>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>

<div id="id" style="display:none">Swal.fire</div>
@Html.Raw(TempData["EpisodeAlert"])

<br />

<div class="dropdown">
	<button class="btn btn-outline-primary dropdown-toggle" type="button" data-toggle="dropdown" id="dropdownBtn">
		@ViewData["SortName"]
	</button>
	<div class="dropdown-menu">
		<a class="dropdown-item" href="@("/PreviewAlbum/Episode?uid=" + ViewBag.titleUID + "&&sort=1")">수정일 (오름차순)</a>
		<a class="dropdown-item" href="@("/PreviewAlbum/Episode?uid=" + ViewBag.titleUID + "&&sort=2")">수정일 (내림차순)</a>
		<a class="dropdown-item" href="@("/PreviewAlbum/Episode?uid=" + ViewBag.titleUID + "&&sort=3")">번호 (오름차순)</a>
		<a class="dropdown-item" href="@("/PreviewAlbum/Episode?uid=" + ViewBag.titleUID + "&&sort=4")">번호 (내림차순)</a>
	</div>

	@if (isAdmin)
	{
		<button type="button" name="ProcessNumber" class="btn btn-md btn-lg col-2" style="float: right; color: white; background-color: lightseagreen;" value=1 onclick="location.href='@Url.Action("AddEpisode", "PreviewAdmin")'">추가</button>
	}
</div>

&nbsp;

<main>



	@*<div class="album py-5 bg-light">*@
	<div class="album @*py-5*@">
		<div class="container">
			@*<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">*@
			<div class="row row-cols-3 g-3">
				@foreach (EpisodeData item in ViewBag.EpisodeList)
				{
					<div class="col">
						<div class="card shadow-sm">
							@*<svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c" /><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>*@
							@*<img class="card-img-top" src="~/SuperLarva.jpg" alt="Card image cap">*@
							<img class="card-img-top" src=@item.ImagePath alt="Card image cap">
							@*<a class="card-block stretched-link text-decoration-none" href="http://192.168.99.44:59683/Review/Comment"></a>*@
							
@*							@if (isAdmin)
							{
								<a class="card-block stretched-link text-decoration-none" href=@("VideoManager/Review/Comment?uid=" + item.Uid)></a>
							}
							else
							{
								<a class="card-block stretched-link text-decoration-none" href=@("VideoManager/Review/Comment?uid=" + item.Uid)></a>
							}*@

							<a class="card-block stretched-link text-decoration-none" href=@Url.Action("Comment","PreviewReview", new {uid = item.Uid} )></a>

							<div class="card-body" href="#">


								<div>
									<fieldset class="rating">
										<input type="radio" id=@str value="5" @starCheck[ratingJ, 9] onclick="return(false);" />
										<label class="full" for=@str title=@str></label>
										@{
											ratingI++;
											str = "star25" + ratingI.ToString();
										}
									<input type="radio" id=@str value="4.5" @starCheck[ratingJ, 8] onclick="return(false);" />
										<label class="half" for=@str title=@str></label>
										@{
											ratingI++;
											str = "star25" + ratingI.ToString();
										}
										<input type="radio" id=@str value="4" @starCheck[ratingJ, 7] onclick="return(false);" />
										<label class="full" for=@str title=@str></label>
										@{
											ratingI++;
											str = "star25" + ratingI.ToString();
										}
										<input type="radio" id=@str value="3.5" @starCheck[ratingJ, 6] onclick="return(false);" />
										<label class="half" for=@str title=@str></label>
										@{
											ratingI++;
											str = "star25" + ratingI.ToString();
										}
										<input type="radio" id=@str value="3" @starCheck[ratingJ, 5] onclick="return(false);" />
										<label class="full" for=@str title=@str></label>
										@{
											ratingI++;
											str = "star25" + ratingI.ToString();
										}
										<input type="radio" id=@str value="2.5" @starCheck[ratingJ, 4] onclick="return(false);" />
										<label class="half" for=@str title=@str></label>
										@{
											ratingI++;
											str = "star25" + ratingI.ToString();
										}
										<input type="radio" id=@str value="2" @starCheck[ratingJ, 3] onclick="return(false);" />
										<label class="full" for=@str title=@str></label>
										@{
											ratingI++;
											str = "star25" + ratingI.ToString();
										}
										<input type="radio" id=@str value="1.5" @starCheck[ratingJ, 2] onclick="return(false);" />
										<label class="half" for=@str title=@str></label>
										@{
											ratingI++;
											str = "star25" + ratingI.ToString();
										}
										<input type="radio" id=@str value="1" @starCheck[ratingJ, 1] onclick="return(false);" />
										<label class="full" for=@str title=@str></label>
										@{
											ratingI++;
											str = "star25" + ratingI.ToString();
										}
										<input type="radio" id=@str value="0.5" @starCheck[ratingJ, 0] onclick="return(false);" />
										<label class="half" for=@str title=@str></label>
									</fieldset>
									&nbsp;
								</div>

								&nbsp;

								<div class="card-text">@("NO." + item.SortNumber)</div>
								<div class="card-text">@item.EpisodeName</div>
								<small class="text-muted">@item.Date</small>

								@if (isAdmin)
								{
									<div class="d-flex justify-content-between align-items-center">
										<div class="btn-group">
											<form class="form" method="post" asp-controller="PreviewAdmin" asp-action="AddEpisode">
												<input type="hidden" name="EpisodeName" value="@item.EpisodeName">
												<input type="hidden" name="SortNumber" value=@item.SortNumber>
												<input type="hidden" name="Whatwork1" value=@item.Whatwork1>
												<input type="hidden" name="Whatwork2" value=@item.Whatwork2>
												<input type="hidden" name="Whatwork3" value=@item.Whatwork3>
												<input type="hidden" name="imagePath" value=@item.ImagePath>
												<input type="hidden" name="AnimeticPath" value=@item.AnimeticPath>
												<input type="hidden" name="AnimationPath" value=@item.AnimationPath>
												<input type="hidden" name="FinalPath" value=@item.FinalPath>
												<input type="hidden" name="uid" value=@item.Uid>
												<input type="hidden" name="processNumber" value=2>
												<button type="submit" class="btn btn-sm btn-outline-secondary" onclick="location.href='@Url.Action("AddEpisode","PreviewAdmin")'">수정</button>
											</form>
											@*<button type="button" class="btn btn-sm btn-outline-secondary" onclick="location.href='/Admin/AddTitle'">수정</button>*@
											@*<button type="button" class="btn btn-sm btn-outline-secondary">삭제</button>*@

											<div class="space">
											</div>

											<form method="post" asp-controller="PreviewAdmin" asp-action="DeleteEpisode" onclick="return confirm('에피소드를 삭제 하시겠습니까?')">
												<input type="hidden" name="episodeUid" value=@item.Uid>
												<button type="submit" class="btn btn-sm btn-outline-secondary">삭제</button>
											</form>
										</div>
									</div>
								}



								@{
									ratingI++;
									str = "star25" + ratingI.ToString();
									ratingJ++;
								}

								@*<div class="d-flex justify-content-between align-items-center">*@
							</div>
						</div>
					</div>
				}








			</div>
		</div>
	</div>
</main>

tubaNWeb/Views/PreviewAlbum/Title.cshtml
@using tubaNWeb.Models.Preview

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
	Layout = "_LayoutPreview";
	ViewData["Title"] = "시즌";

	bool isAdmin = false;
	if (Context.Session.GetString("UserId") != null)
	{
		string userId = Context.Session.GetString("UserId");
		if (userId.ToLower().Equals("admin"))
		{
			isAdmin = true;
		}
	}
}



<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
<style>
	/*	.bd-placeholder-img {
			font-size: 1.125rem;
			text-anchor: middle;
			-webkit-user-select: none;
			-moz-user-select: none;
			user-select: none;
		}

		@@media (min-width: 768px) {
			.bd-placeholder-img-lg {
				font-size: 3.5rem;
			}
		}*/



	.container {
		padding-left: 0;
		width: 1400px !important;
		max-width: none !important;
		overflow: hidden; /*어긋난 정렬 수정*/
	}

	@@media (max-width: 300px) {
		.container {
			width: 300px !important;
		}
	}

	/*카드 이미지 크기조절*/
	.card-img-top {
		height: 15rem;
		/*object-fit: cover;*/
		background-size: cover;
	}

	/*카드 버튼 위로*/
	.card .btn {
		z-index: 2;
		position: relative;
	}

	.space {
		width: 5px;
		height: auto;
		display: inline-block;
	}
</style>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>

<div id="id" style="display:none">Swal.fire</div>
@Html.Raw(TempData["TitleAlert"])

@*<hr />*@
<br />

<div class="dropdown">
	<button class="btn btn-outline-primary dropdown-toggle" type="button" data-toggle="dropdown" id="dropdownBtn">
		@ViewData["SortName"]
	</button>
	<div class="dropdown-menu">
		<a class="dropdown-item" href="@Url.Action("Title", "PreviewAlbum", new { sort = 1})">수정일 (오름차순)</a>
		<a class="dropdown-item" href="@Url.Action("Title", "PreviewAlbum", new { sort = 2})">수정일 (내림차순)</a>
		<a class="dropdown-item" href="@Url.Action("Title", "PreviewAlbum", new { sort = 3})">번호 (오름차순)</a>
		<a class="dropdown-item" href="@Url.Action("Title", "PreviewAlbum", new { sort = 4})">번호 (내림차순)</a>
	</div>

	@if (isAdmin)
	{
		@*<button type="button" name="ProcessNumber" class="btn btn-md btn-lg col-2" style="float: right; color: white; background-color: lightseagreen;" value=1 onclick="location.href='VideoManager/Admin/AddTitle'">추가</button>*@
		<button type="button" name="ProcessNumber" class="btn btn-md btn-lg col-2" style="float: right; color: white; background-color: lightseagreen;" value=1 onclick="location.href='@Url.Action("AddTitle","PreviewAdmin")'">추가</button>
	}
</div>

&nbsp;

<main>
	<div class="album @*py-5*@">
		<div class="container">

			<div class="row row-cols-3 g-3">

				@foreach (Video item in ViewBag.TitleList)
				{
					<div class="col">
						<div class="card shadow-sm">
							@*<svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c" /><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>*@
							@*<img class="card-img-top" src="~/SuperLarva.jpg" alt="Card image cap">*@
							<img class="card-img-top" src=@item.ImageLink alt="Card image cap">
							@*<a class="card-block stretched-link text-decoration-none" href="http://192.168.99.44:59683/Review/Comment"></a>*@
@*							@if (isAdmin)
							{
								<a class="card-block stretched-link text-decoration-none" href=@("Episode?uid=" + item.UID + "&&sort=1")></a>
							}
							else
							{
								<a class="card-block stretched-link text-decoration-none" href=@("Episode?uid=" + item.UID + "&&sort=1")></a>								
							}*@

							<a class="card-block stretched-link text-decoration-none" href=@Url.Action("Episode","PreviewAlbum", new { uid = item.UID, sort = 1})></a>

							<div class="card-body" href="#">
								<div class="card-text">@("NO." + item.SortNumber)</div>
								<div class="card-text">@item.Name</div>
								<small class="text-muted">@item.Date</small>

								@if (isAdmin)
								{
									<div class="d-flex justify-content-between align-items-center">
										<div class="btn-group">
											<form method="post" asp-controller="PreviewAdmin" asp-action="AddTitle">
												<input type="hidden" name="titleName" value="@item.Name">
												<input type="hidden" name="sortNumber" value=@item.SortNumber>
												<input type="hidden" name="imagePath" value=@item.ImageLink>
												<input type="hidden" name="processNumber" value=2>
												<input type="hidden" name="uid" value=@item.UID>
												<button type="submit" class="btn btn-sm btn-outline-secondary" @*onclick="location.href='/Admin/AddTitle'"*@>수정</button>
											</form>

											<div class="space">
											</div>

											<form method="post" asp-controller="PreviewAdmin" asp-action="DeleteTitle" onclick="return confirm('시즌을 삭제 하시겠습니까?')">
												<input type="hidden" name="titleUid" value=@item.UID>
												<button type="submit" class="btn btn-sm btn-outline-secondary">삭제</button>
											</form>

											@*											<button type="button" class="btn btn-sm btn-outline-secondary" onclick="location.href='/Admin/AddTitle'">수정</button>
									<button type="button" class="btn btn-sm btn-outline-secondary">삭제</button>*@
										</div>
									</div>
								}
							</div>
						</div>
					</div>
				}








			</div>
		</div>
	</div>


</main>